### PR TITLE
WIP: Auto-generate stream key at first start

### LINKED ISSUE #11: TODO: Better stream key system
As of right now the stream key is hard coded. This is insecure and not production ready.

IDEAS:

-On first time startup create a stream key and cache it on the system. This will then be output to the user in order to put into obs. This will need to support the ability to generate a new key in case it gets leaked

-Take the stream key as an argument and allow the orchestrator to handle it

### PR DESCRIPTION
**Pull request by obviyus**
Fixes #11. Extremely basic stream-key generation:
- `stream_key` is generated at first launch and **saved as plaintext**
- subsequent launches just pull the key from the file on disk

### CODE REVIEW

**Comment by GRVYDEV** [comment]
This is looking great so far!!!

**Comment by obviyus** [comment]
`stream_key` is now stored as hex on disk.

**Comment by GRVYDEV** [comment]
Looks great! Has this been tested in docker as well?

**Comment by obviyus** [comment]
> Looks great! Has this been tested in docker as well?

No, not yet. To use with docker, I presume we'll need to account for the `stream_key` being an environment variable? I could add a check to see if the `STREAM_KEY` env var exists, and:
- if not, proceed as normal
- if it does, use that instead

However, do we want to give the user the ability to provide the stream key?

**Comment by GRVYDEV** [comment]
> > Looks great! Has this been tested in docker as well?
> 
> No, not yet. To use with docker, I presume we'll need to account for the `stream_key` being an environment variable? I could add a check to see if the `STREAM_KEY` env var exists, and:
> 
>     * if not, proceed as normal
> 
>     * if it does, use that instead
> 
> 
> However, do we want to give the user the ability to provide the stream key?

I dont think we should give the user the ability to provide a stream key as long as we show it to them every time on startup. Also have you built a mechanism for the regeneration of a key if it were to get leaked?

**Comment by obviyus** [comment]
> I dont think we should give the user the ability to provide a stream key as long as we show it to them every time on startup. Also have you built a mechanism for the regeneration of a key if it were to get leaked?

Not yet, one _workaround_ would be to just delete the file on disk and that would automatically trigger a new key. 

Any ideas on how to go about using a manual trigger (keyboard shortcuts)?

**Review by GRVYDEV — APPROVED** [review]
Awesome thank you!

**Pull request merged**
